from __future__ import annotations

# Reference Data: system-managed value lists constraining PO fields.
# Frontend renders these as dropdowns; backend validates against them.

CURRENCIES: tuple[tuple[str, str], ...] = (
    ("AED", "UAE Dirham"),
    ("AUD", "Australian Dollar"),
    ("BDT", "Bangladeshi Taka"),
    ("BRL", "Brazilian Real"),
    ("CAD", "Canadian Dollar"),
    ("CHF", "Swiss Franc"),
    ("CNY", "Chinese Yuan"),
    ("DKK", "Danish Krone"),
    ("EUR", "Euro"),
    ("GBP", "British Pound"),
    ("HKD", "Hong Kong Dollar"),
    ("IDR", "Indonesian Rupiah"),
    ("INR", "Indian Rupee"),
    ("JPY", "Japanese Yen"),
    ("KRW", "South Korean Won"),
    ("MXN", "Mexican Peso"),
    ("MYR", "Malaysian Ringgit"),
    ("NOK", "Norwegian Krone"),
    ("NZD", "New Zealand Dollar"),
    ("PHP", "Philippine Peso"),
    ("PKR", "Pakistani Rupee"),
    ("SAR", "Saudi Riyal"),
    ("SEK", "Swedish Krona"),
    ("SGD", "Singapore Dollar"),
    ("THB", "Thai Baht"),
    ("TRY", "Turkish Lira"),
    ("TWD", "Taiwan Dollar"),
    ("USD", "US Dollar"),
    ("VND", "Vietnamese Dong"),
    ("ZAR", "South African Rand"),
)

INCOTERMS: tuple[tuple[str, str], ...] = (
    ("CFR", "Cost and Freight"),
    ("CIF", "Cost, Insurance and Freight"),
    ("CIP", "Carriage and Insurance Paid To"),
    ("CPT", "Carriage Paid To"),
    ("DAP", "Delivered at Place"),
    ("DDP", "Delivered Duty Paid"),
    ("DPU", "Delivered at Place Unloaded"),
    ("EXW", "Ex Works"),
    ("FAS", "Free Alongside Ship"),
    ("FCA", "Free Carrier"),
    ("FOB", "Free on Board"),
)

PAYMENT_TERMS: tuple[tuple[str, str], ...] = (
    ("DA", "Documents against Acceptance"),
    ("DP", "Documents against Payment"),
    ("LC", "Letter of Credit"),
    ("TT", "Telegraphic Transfer"),
)

COUNTRIES: tuple[tuple[str, str], ...] = (
    ("AE", "United Arab Emirates"),
    ("AU", "Australia"),
    ("BD", "Bangladesh"),
    ("BR", "Brazil"),
    ("CA", "Canada"),
    ("CH", "Switzerland"),
    ("CN", "China"),
    ("DE", "Germany"),
    ("DK", "Denmark"),
    ("EG", "Egypt"),
    ("ES", "Spain"),
    ("FR", "France"),
    ("GB", "United Kingdom"),
    ("HK", "Hong Kong"),
    ("ID", "Indonesia"),
    ("IN", "India"),
    ("IT", "Italy"),
    ("JP", "Japan"),
    ("KR", "South Korea"),
    ("MX", "Mexico"),
    ("MY", "Malaysia"),
    ("NL", "Netherlands"),
    ("PH", "Philippines"),
    ("PK", "Pakistan"),
    ("SA", "Saudi Arabia"),
    ("SG", "Singapore"),
    ("TH", "Thailand"),
    ("TR", "Turkey"),
    ("US", "United States"),
    ("VN", "Vietnam"),
)

PORTS: tuple[tuple[str, str], ...] = (
    ("AEAUH", "Abu Dhabi"),
    ("AEJEA", "Jebel Ali"),
    ("AUMEL", "Melbourne"),
    ("AUSYD", "Sydney"),
    ("BDDAC", "Chittagong"),
    ("BRPNG", "Paranagua"),
    ("BRSSZ", "Santos"),
    ("CAVAN", "Vancouver"),
    ("CNNGB", "Ningbo"),
    ("CNQIN", "Qingdao"),
    ("CNSHA", "Shanghai"),
    ("CNSZX", "Shenzhen"),
    ("CNTAO", "Qingdao"),
    ("CNTXG", "Tianjin"),
    ("CNXMN", "Xiamen"),
    ("DEBRV", "Bremerhaven"),
    ("DEHAM", "Hamburg"),
    ("EGALY", "Alexandria"),
    ("EGPSD", "Port Said"),
    ("ESBCN", "Barcelona"),
    ("ESVLC", "Valencia"),
    ("FRFOS", "Marseille"),
    ("FRLEH", "Le Havre"),
    ("GBFXT", "Felixstowe"),
    ("GBSOU", "Southampton"),
    ("GRGIT", "Gioia Tauro"),
    ("GRPIR", "Piraeus"),
    ("HKHKG", "Hong Kong"),
    ("IDTPP", "Tanjung Priok"),
    ("INMUN", "Mundra"),
    ("INNSA", "Nhava Sheva"),
    ("ITGOA", "Genoa"),
    ("JPKOB", "Kobe"),
    ("JPTYO", "Tokyo"),
    ("JPYOK", "Yokohama"),
    ("KRPUS", "Busan"),
    ("MXMAN", "Manzanillo"),
    ("MYPKG", "Port Klang"),
    ("MYTPP", "Tanjung Pelepas"),
    ("NLRTM", "Rotterdam"),
    ("PHMNL", "Manila"),
    ("PKKHI", "Karachi"),
    ("SAJED", "Jeddah"),
    ("SGSIN", "Singapore"),
    ("THBKK", "Bangkok"),
    ("THLCH", "Laem Chabang"),
    ("TRIST", "Istanbul"),
    ("TWKHH", "Kaohsiung"),
    ("USHOU", "Houston"),
    ("USLAX", "Los Angeles"),
    ("USLGB", "Long Beach"),
    ("USNYC", "New York"),
    ("USSAV", "Savannah"),
    ("VNHPH", "Hai Phong"),
    ("VNSGN", "Ho Chi Minh City"),
    ("ZADUR", "Durban"),
)

# Lookup sets for fast validation
VALID_CURRENCIES: frozenset[str] = frozenset(code for code, _ in CURRENCIES)
VALID_INCOTERMS: frozenset[str] = frozenset(code for code, _ in INCOTERMS)
VALID_PAYMENT_TERMS: frozenset[str] = frozenset(code for code, _ in PAYMENT_TERMS)
VALID_COUNTRIES: frozenset[str] = frozenset(code for code, _ in COUNTRIES)
VALID_PORTS: frozenset[str] = frozenset(code for code, _ in PORTS)
